apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-pv
spec:
  storageClassName: manual
  claimRef:
    name: mongodb-data-pvc
    namespace: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/mongodb-data"