apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-config-pv
spec:
  storageClassName: manual
  claimRef:
    name: mongodb-config-pvc
    namespace: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/mongodb-config"