apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
  labels:
    component: mongodb
    resiliency: single
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    component: mongodb
    resiliency: single